components:
  guacamole:
    state: enabled
  workspace_definitions:
    repository:
      path: sandbox
      requiresAuth: true
      url: https://github.com/lsc-sde/iac-flux-workspace-definitions
      secret:
        usernameKey: WorkspaceReposPatUser
        passwordKey: WorkspaceReposPatToken
