
components:
  aks_dns:
    repository:
      branch: main
  analytics_workspace_management:
    repository:
      branch: "release/0.1.19"
  cert_manager:
    repository:
      branch: "release/0.1.40"
  github_runner:
    repository:
      branch: "release/0.1.56"
  ingress_nginx:
    repository:
      branch: "release/0.1.61"
  jupyter_hub:
    repository:
      branch: "release/0.2.105"
  keda:
    repository:
      branch: "release/0.1.44"
  metrics_server:
    repository:
      branch: main
  ohdsi:
    repository:
      branch: "release/0.1.68"
  secrets_distributor:
    repository:
      branch: "release/0.1.6"
  guacamole:
    repository:
      branch: release/0.1.21
  superset:
    repository:
      branch: release/0.1.16
  rabbitmq:
    repository:
      branch: release/0.1.20
  observability_metrics:
    repository:
      branch: release/0.1.42
  keycloak:
    repository:
      branch: release/0.1.70
  awms_guacamole:
    repository:
      branch: release/0.1.28
  observability-metrics:
    repository:
      branch: release/0.1.45
