
components:
  aks_dns:
    repository:
      branch: main
  analytics_workspace_management:
    repository:
      branch: "release/0.1.15"
  cert_manager:
    repository:
      branch: "release/0.1.37"
  github_runner:
    repository:
      branch: "release/0.1.56"
  ingress_nginx:
    repository:
      branch: "release/0.1.59"
  jupyter_hub:
    repository:
      branch: "release/0.2.101"
  keda:
    repository:
      branch: "release/0.1.42"
  metrics_server:
    repository:
      branch: main
  ohdsi:
    repository:
      branch: "release/0.1.68"
  secrets_distributor:
    repository:
      branch: "release/0.1.5"
  guacamole:
    repository:
      branch: release/0.1.19
  superset:
    repository:
      branch: release/0.1.16
  rabbitmq:
    repository:
      branch: release/0.1.18
  observability_metrics:
    repository:
      branch: release/0.1.42
  keycloak:
    repository:
      branch: release/0.1.70
  awms_guacamole:
    repository:
      branch: release/0.1.20
