components:
  keycloak:
    image: lscsde/awms-keycloak:0.1.9
  awms_guacamole:
    image: lscsde/awms-guacamole-operator:0.1.28
  awms_crate:
    image: lscsde/awms-crate-operator:0.1.5
  awms_datasource:
    image: lscsde/awms-datasource-operator:0.1.4
  secrets_distributor:
    image: lscsde/secrets-distributor:0.1.31
  cr8tor_approval_service:
    image: ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-approval-service:0.1.52
  cr8tor_metadata_service:
    image: ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-metadata-service:0.1.52
  cr8tor_publish_service:
    image: ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-publish-service:0.1.52