components:
  cr8tor_approval_service:
    image: ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-approval-service:0.1.52
  cr8tor_metadata_service:
    image: ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-metadata-service:0.1.52
  cr8tor_publish_service:
    image: ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-publish-service:0.1.52