apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github-runner
  namespace: github-runner
spec:
  interval: 1m0s
  ref:
    branch: ${github_runner_branch}
  timeout: 60s
  url: https://github.com/lsc-sde/iac-flux-github-action-runners