apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lscsde-config
configMapGenerator:
  - name: environment-component-config-sjt
    files:
      - values.yaml=environment-component-config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
- configuration.yaml
- release-namespaces.yaml
- release.yaml