apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secrets-storage
spec:
  storageClassName: local-path #secrets-storage
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi