volumeMounts:
  - name: secrets-store-inline
    mountPath: /mnt/secrets
    readOnly: true
volumes:
  - name: secrets-store-inline
    hostPath:
      path: /Users/mph/Documents/nhs/lsc/secrets
      type: Directory