volumeMounts:
  - name: secrets-store-inline
    mountPath: /mnt/secrets
    readOnly: true
volumes:
  - name: secrets-store-inline
    hostPath:
      path:  /var/lib/rancher/k3s/storage/secrets
      type: Directory