kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: secrets-storage
provisioner:  microk8s.io/hostpath #rancher.io/local-path
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/secrets
volumeBindingMode: WaitForFirstConsumer