apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sync
  namespace: secrets-distributor
  annotations:
    xlscsde.nhs.uk/secretUsage: "Key Vault Sync"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${azure_client_id}
    keyvaultName: ${azure_keyvault_name}
    tenantId: "${azure_tenant_id}"
    objects: |
        array:
        - |
          objectName: PrimaryStorageAccountName
          objectType: secret
        - |
          objectName: PrimaryStorageAccountKey
          objectType: secret
        - |
          objectName: JupyterClientSecret
          objectType: secret
        - |
          objectName: WildcardCertificate
          objectType: secret
        - |
          objectName: WildcardCertificateKey
          objectType: secret
        - |
          objectName: PatToken
          objectType: secret
        - |
          objectName: SqlHostName
          objectType: secret
        - |
          objectName: SqlAdministratorLogin
          objectType: secret
        - |
          objectName: SqlAdministratorPassword
          objectType: secret