apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  environment_name: local
  lscsde_components_branch: main
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
data:
  azure_client_id: "not-applicable"
  azure_keyvault_name: "not-applicable"
  azure_storage_account: "not-applicable"
  azure_tenant_id: "not-applicable"
  private_dnz_zone: "not-applicable"
  dns_prefix: "lscsde.local"
  dns_resource_group: "not-applicable"
  dns_subscription_id: "not-applicable"
  azure_subscription_id: "not-applicable"
  azure_sql_server: "cluster.lsc-sde.local"
  azure_resource_group: "not-applicable"
  azure_location: "not-applicable"
  postgresql_server: "cluster.lsc-sde.local"
  postgresql_username: "pgsql"
  jupyterhub_client_id: "jupyterhub"
  jupyterhub_users_role: "jupyter-users"
  jupyterhub_admins_role: "jupyter-admins"
  ohdsi_client_id: "ohdsi"